language: go

go:
  - 1.10.x
  - master

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - npm install -g typescript
  - go get -u github.com/aerogo/pack
  - go install github.com/aerogo/pack
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/before-script.sh)

script:
  - tsc
  - pack
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/script.sh)

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/blitzprog/gotravis/master/after-success.sh)